package Interface;

import Info.Communication;
import Info.PDU;
import java.io.*;
import java.net.*;
import java.util.*;

/**
 *
 * @author Grupo 04
 */

public class Main extends javax.swing.JFrame {
    private int udpPORT;
    private DatagramSocket server = null;
    private InetAddress IPAddress;
    private Communication s;
    
    public Main() {
        PDU hello, response = null;
        try{
            this.udpPORT = 9876;
            this.server = new DatagramSocket();
            this.IPAddress = InetAddress.getLocalHost();
            byte[] incomingData = new byte[1024];
            hello = new PDU(1,0,0,new ArrayList<>());
            this.s = new Communication(this.udpPORT, this.IPAddress);
            this.s.sendPDU(hello); 
            response = this.s.receivePDU();                
        } catch (IOException e) {
            System.out.println("Ocorreu um erro na execução do Cliente");
        } finally { server.close(); }
        
        initComponents();
        this.setLocationRelativeTo(null);
    }
    
    public Main(Communication s) {
        this.s = s;      
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        registerButton = new javax.swing.JButton();
        quitButton = new javax.swing.JButton();
        loginButton = new javax.swing.JButton();

        setTitle("Log in");
        setResizable(false);

        registerButton.setText("Register");
        registerButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                onClickLogInButton(evt);
            }
        });

        quitButton.setText("Sair");
        quitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                quitButtononClickLogInButton(evt);
            }
        });

        loginButton.setText("Login");
        loginButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginButtononClickLogInButton(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(120, 120, 120)
                .addComponent(loginButton, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(registerButton, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(120, 120, 120))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(185, 185, 185)
                .addComponent(quitButton, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(185, 185, 185))
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {loginButton, quitButton, registerButton});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(89, 89, 89)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(loginButton, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(registerButton, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(quitButton, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(89, 89, 89))
        );

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {loginButton, quitButton, registerButton});

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void onClickLogInButton(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_onClickLogInButton
        Register r = new Register(this.s);
        r.setVisible(true);
        this.dispose(); 
    }//GEN-LAST:event_onClickLogInButton

    private void quitButtononClickLogInButton(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_quitButtononClickLogInButton
        System.exit(0);  
    }//GEN-LAST:event_quitButtononClickLogInButton

    private void loginButtononClickLogInButton(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginButtononClickLogInButton
        Login l = new Login(this.s);
        l.setVisible(true);
        this.dispose();   
    }//GEN-LAST:event_loginButtononClickLogInButton

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new Main().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton loginButton;
    private javax.swing.JButton quitButton;
    private javax.swing.JButton registerButton;
    // End of variables declaration//GEN-END:variables

}
