
package Interface;

import Info.Communication;
import Info.Fields;
import Info.PDU;
import Info.PlayerMP3;
import java.awt.image.BufferedImage;
import java.io.File;
import java.io.IOException;
import java.net.SocketException;
import java.util.*;
import javax.swing.ImageIcon;

/**
 *
 * @author Grupo 04
 */
public class Question extends javax.swing.JFrame {
    private String user;
    private Communication s;
    private String desafio;
    private String questao;
    private int escolha;
    private PlayerMP3 mp3;
    private Timer timer;
    public Question(String user, String desafio, String numero, String pergunta, HashMap<Integer,String> respostas, BufferedImage img, File music, Communication s) {
        initComponents();
        this.s = s;
        this.user = user;
        this.questao = numero;
        this.desafio = desafio;
        this.nPergunta.setText(numero);
        this.TPergunta.setText(pergunta);
        this.jRadioButton2.setText(respostas.get(1));
        this.jRadioButton3.setText(respostas.get(2));
        this.jRadioButton4.setText(respostas.get(3));
        this.imagem.setIcon(new ImageIcon(img.getScaledInstance(this.imagem.getWidth(),this.imagem.getHeight(), BufferedImage.SCALE_DEFAULT)));
        this.jButton4.setEnabled(false);
        this.jButton1.setEnabled(false);
        this.mp3 = new PlayerMP3("Musica.mp3");
        mp3.play();
        this.timer = new Timer();
        
        timer.schedule(new TimerTask() {
            @Override
            public void run() {
                askQuestion();
            }
        }, 60*1000);
    }
    
    private void askQuestion() {                                         
        //Passou o tempo 
        mp3.close();
        ArrayList<Fields> list = new ArrayList<>();
        list.add(new Fields(6, String.valueOf(-1)));
        list.add(new Fields(7, this.desafio));
        list.add(new Fields(10, this.questao));
        byte[] r;
        PDU receive;
        List<Fields> campos = null;
        
        try {
            r = Communication.serializa(list);
            PDU answer = new PDU(11,list.size(),r.length,list);
            this.s.sendPDU(answer);
            receive = this.s.receivePDU();
            campos = receive.getCampos();
        } catch (IOException ex) { new OkDialog(this).show("Ocorreu um erro!!"); }
            
        if(campos != null){
            if(campos.get(campos.indexOf(new Fields(14,""))).getInfo().equals("OK")) {
                String pontos = campos.get(campos.indexOf(new Fields(15,""))).getInfo();
                new OkDialog(this).show("Resposta correta! Obteve " + pontos + "!\n");
            } else {
                String pontos = campos.get(campos.indexOf(new Fields(15,""))).getInfo();
                new OkDialog(this).show("Resposta errada! Obteve " + pontos + "!\n");
            }
        }
        
        if(!this.questao.equals("10")){
            playChallenge jogo = new playChallenge(this.desafio,this.user,this.questao+1,this.s);
            try {
                jogo.prepareQuestion();
                this.dispose();
            } catch (SocketException ex) {
                new OkDialog(this).show("Ocorreu um erro ao preparar a pergunta!");
            }  
        } else{
            this.jButton4.setEnabled(true);
            this.jButton3.setEnabled(false);
            this.jButton1.setEnabled(false);
            this.jButton5.setEnabled(true);
            this.jRadioButton2.setEnabled(false);
            this.jRadioButton3.setEnabled(false);
            this.jRadioButton4.setEnabled(false);
        }  
    }
   
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup4 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        imagem = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jRadioButton3 = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();
        jRadioButton4 = new javax.swing.JRadioButton();
        jButton1 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        Opcoes = new javax.swing.JLabel();
        jButton5 = new javax.swing.JButton();
        TPergunta = new javax.swing.JLabel();
        Pergunta = new javax.swing.JLabel();
        nPergunta = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jPanel1.setPreferredSize(new java.awt.Dimension(800, 500));

        imagem.setBackground(new java.awt.Color(51, 51, 51));
        imagem.setText("A imagem aparece aqui");
        imagem.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        buttonGroup4.add(jRadioButton3);
        jRadioButton3.setText("Opção 2.");
        jRadioButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton3ActionPerformed(evt);
            }
        });

        buttonGroup4.add(jRadioButton2);
        jRadioButton2.setText("Opção 1.");
        jRadioButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton2ActionPerformed(evt);
            }
        });

        buttonGroup4.add(jRadioButton4);
        jRadioButton4.setText("Opção 3.");
        jRadioButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton4ActionPerformed(evt);
            }
        });

        jButton1.setText("Answer");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton3.setText("Quit");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setText("End");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        Opcoes.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        Opcoes.setText("Opções:");

        jButton5.setText("Logout");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(Opcoes, javax.swing.GroupLayout.PREFERRED_SIZE, 246, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jRadioButton2, javax.swing.GroupLayout.DEFAULT_SIZE, 246, Short.MAX_VALUE)
                                .addComponent(jRadioButton4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jRadioButton3, javax.swing.GroupLayout.DEFAULT_SIZE, 246, Short.MAX_VALUE))))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(39, 39, 39)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jButton1)
                                .addGap(10, 10, 10)
                                .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(10, 10, 10)
                                .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGap(15, 15, 15))
        );

        jPanel3Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jButton1, jButton3, jButton4, jButton5});

        jPanel3Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jRadioButton2, jRadioButton3, jRadioButton4});

        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(60, 60, 60)
                .addComponent(Opcoes)
                .addGap(18, 18, 18)
                .addComponent(jRadioButton2)
                .addGap(20, 20, 20)
                .addComponent(jRadioButton3)
                .addGap(20, 20, 20)
                .addComponent(jRadioButton4)
                .addGap(20, 20, 20)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton3))
                .addGap(11, 11, 11)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton5))
                .addContainerGap(53, Short.MAX_VALUE))
        );

        jPanel3Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {Opcoes, jRadioButton2, jRadioButton3, jRadioButton4});

        jPanel3Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {jButton1, jButton3, jButton4, jButton5});

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(49, 49, 49)
                .addComponent(imagem, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 26, Short.MAX_VALUE)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(49, 49, 49))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(imagem, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(25, Short.MAX_VALUE))
        );

        TPergunta.setText("TEXTO DA PERGUNTA");

        Pergunta.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        Pergunta.setText("Pergunta ");

        nPergunta.setText("NR:");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(80, Short.MAX_VALUE)
                .addComponent(Pergunta)
                .addGap(0, 0, 0)
                .addComponent(nPergunta, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(50, 50, 50)
                .addComponent(TPergunta, javax.swing.GroupLayout.PREFERRED_SIZE, 533, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(43, 43, 43))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TPergunta, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Pergunta)
                    .addComponent(nPergunta))
                .addContainerGap(437, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                    .addGap(0, 65, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        jPanel1Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {Pergunta, TPergunta, nPergunta});

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 810, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jRadioButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton2ActionPerformed
        this.jButton1.setEnabled(true);
        this.timer.cancel();
        this.escolha = 1;
    }//GEN-LAST:event_jRadioButton2ActionPerformed

    private void jRadioButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton3ActionPerformed
        this.jButton1.setEnabled(true);
        this.timer.cancel();
        this.escolha = 2;
    }//GEN-LAST:event_jRadioButton3ActionPerformed

    private void jRadioButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton4ActionPerformed
        this.jButton1.setEnabled(true);
        this.timer.cancel();
        this.escolha = 3;
    }//GEN-LAST:event_jRadioButton4ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        //Responder á questão
        mp3.close();
        this.timer.cancel();
        ArrayList<Fields> list = new ArrayList<>();
        list.add(new Fields(6, String.valueOf(this.escolha)));
        list.add(new Fields(7, this.desafio));
        list.add(new Fields(10, this.questao));
        byte[] r;
        PDU receive;
        List<Fields> campos = null;
        
        try {
            r = Communication.serializa(list);
            PDU answer = new PDU(11,list.size(),r.length,list);
            this.s.sendPDU(answer);
            receive = this.s.receivePDU();
            campos = receive.getCampos();
        } catch (IOException ex) { new OkDialog(this).show("Ocorreu um erro!!"); }
            
        if(campos != null){
            if(campos.get(campos.indexOf(new Fields(14,""))).getInfo().equals("OK")) {
                String pontos = campos.get(campos.indexOf(new Fields(15,""))).getInfo();
                new OkDialog(this).show("Resposta correta! Obteve " + pontos + "!\n");
            } else {
                String pontos = campos.get(campos.indexOf(new Fields(15,""))).getInfo();
                new OkDialog(this).show("Resposta errada! Obteve " + pontos + "!\n");
            }
        }
        
        if(!this.questao.equals("10")){
            playChallenge jogo = new playChallenge(this.desafio,this.user,this.questao+1,this.s);
            try {
                jogo.prepareQuestion();
                this.dispose();
            } catch (SocketException ex) {
                new OkDialog(this).show("Ocorreu um erro ao preparar a pergunta!");
            }  
        } else{
            this.jButton4.setEnabled(true);
            this.jButton3.setEnabled(false);
            this.jButton1.setEnabled(false);
            this.jButton5.setEnabled(true);
            this.jRadioButton2.setEnabled(false);
            this.jRadioButton3.setEnabled(false);
            this.jRadioButton4.setEnabled(false);
        }  
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // Quit - desistir
        this.timer.cancel();
        ArrayList<Fields> list = new ArrayList<>();
        list.add(new Fields(2, this.user));
        byte[] r;
        PDU receive;
        List<Fields> campos = null;
        
        try {
            r = Communication.serializa(list);
            PDU quit = new PDU(5,list.size(),r.length,list);
            this.s.sendPDU(quit);
            receive = this.s.receivePDU();
            campos = receive.getCampos();
        } catch (IOException ex) { new OkDialog(this).show("Ocorreu um erro!!"); }
            
        if(campos != null){
            if(campos.get(campos.indexOf(new Fields(0,""))).getInfo().equals("OK")) {
                new OkDialog(this).show("Desistiu do desafio!\n");
            }
        } 
        MainMenu mm = new MainMenu(this.s, this.user);
        mm.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // Logout - desiste e abandona a aplicação
        this.timer.cancel();
        ArrayList<Fields> list = new ArrayList<>();
        list.add(new Fields(2, this.user));
        byte[] r;
        PDU receive;
        List<Fields> campos = null;
        
        try {
            r = Communication.serializa(list);
            PDU lout = new PDU(4,list.size(),r.length,list);
            this.s.sendPDU(lout);
            receive = this.s.receivePDU();
            campos = receive.getCampos();
        } catch (IOException ex) { new OkDialog(this).show("Ocorreu um erro!!"); }
            
        if(campos != null){
          if(campos.get(campos.indexOf(new Fields(0,""))).getInfo().equals("OK")) {
                new OkDialog(this).show("Logout efectuado!");
                System.exit(0);
            }
            else { new OkDialog(this).show("Logout não efectuado!"); }
        }
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // End - Score de todos os intervenientes
        ArrayList<Fields> list = new ArrayList<>();
        list.add(new Fields(7, this.desafio));
        byte[] r;
        PDU receive;
        List<Fields> campos = null;
        
        try {
            r = Communication.serializa(list);
            PDU end = new PDU(6,list.size(),r.length,list);
            this.s.sendPDU(end);
            receive = this.s.receivePDU();
            campos = receive.getCampos();
        } catch (IOException ex) { new OkDialog(this).show("Ocorreu um erro!!"); }
            
        if(campos != null){
            if(campos.get(campos.indexOf(new Fields(0,""))).getInfo().equals("OK")) {
                int i = 1;
                HashMap<String, Integer> scores = new HashMap<>();
                while(i < campos.size()){
                    scores.put(campos.get(i).getInfo(),Integer.valueOf(campos.get(i+1).getInfo()));
                    i+=2;
                }
                                
                RankingChallenge t = new RankingChallenge(scores);
                MainMenu mm = new MainMenu(this.s, this.user);
                mm.setVisible(true);
                t.setVisible(true);
                this.dispose(); 
            }
        }
    }//GEN-LAST:event_jButton4ActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Opcoes;
    private javax.swing.JLabel Pergunta;
    private javax.swing.JLabel TPergunta;
    private javax.swing.ButtonGroup buttonGroup4;
    private javax.swing.JLabel imagem;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JRadioButton jRadioButton3;
    private javax.swing.JRadioButton jRadioButton4;
    private javax.swing.JLabel nPergunta;
    // End of variables declaration//GEN-END:variables
}
